### ISSUE TITLE
Conditional Styling of Column depending on Value

### ISSUE THREAD

**Issue by rolanvc** [andyperlitch/angularjs-table#13]
Hi, not really an issue, but more of a question.

How can I style a cell (e.g. change backgroundcolor) given the value of the cell?

I've tried using the template parameter of a column object, for example:
template:"<span ng-style = "get_style(row[column.key])">{{row[column.key]}}</span>"
but this isn't working and the get_style() function is getting called. Is there another way that I may have missed?

Thank you!!

**Comment by rolanvc** [comment]
Nevermind, I found a way, for example:
template: "<span ng-style=\"{'background-color':(column.key=='approved' && row[column.key]==false)?'red':'transparent'}\">{{row[column.key]}} </span>"

Thanks!

**Comment by andyperlitch** [comment]
you dropped this: `</span>`

:stuck_out_tongue:

Lemme know if you have any other questions!

**Comment by andyperlitch** [comment]
You dropped this: `</span>`

😄 

Let me know if you have other questions.

**Comment by rolanvc** [comment]
Thank you!
