### ISSUE TITLE
A way to trigger filtering from an outside field

### ISSUE THREAD

**Issue by talamaska** [andyperlitch/angularjs-table#17]
I was wondering is there a way i can get the search term from some text field outside of the table and perform a server side filtering and update the table with that new filtered data.

**Comment by andyperlitch** [comment]
@talamaska: yes, you can achieve this using the [server-side interaction](https://github.com/andyperlitch/angularjs-table#server-side-interaction) feature of the library. Please have a look at that part of the README. 

You may also want to utilize the `reset()` method on the [table API](https://github.com/andyperlitch/angularjs-table#table-api).

If you have more questions, feel free to post here!
