### ISSUE TITLE
Missing 'selector' from Interface

### ISSUE THREAD

**Issue by ghost** [andyperlitch/angularjs-table#3]
![screen shot 2017-04-14 at 3 07 42 pm](https://cloud.githubusercontent.com/assets/25899229/25042908/80f4cdca-2124-11e7-9264-ec6042c34330.png)
![screen shot 2017-04-14 at 3 09 22 pm](https://cloud.githubusercontent.com/assets/25899229/25042914/87005dec-2124-11e7-9924-4ecd5d7bd406.png)

When using 'selector' in TabelColums and using the interface ng.apMesa.ITableColumn i receive Typ e Errors.

**Comment by andyperlitch** [comment]
Thanks bogdan!
