### ISSUE TITLE
Expandable Rows - row does not reset when switching pages

### ISSUE THREAD

**Issue by ghost** [andyperlitch/angularjs-table#5]
There is an issue with expandable rows.

Actions:
1. Expand the first two events on first page.
2. Go to second page.

Actual Result:
2. On the second page, the first two events are expanded also.

Expected Result:
2. The first two events on the first page should not be expanded.

@andyperlitch pls see [DE508](https://rally1.rallydev.com/#/84551301072ud/detail/defect/112066293636) for a video of the issue

**Comment by andyperlitch** [comment]
Thanks for the report! Fixed in v2.12.3.
